Repository FRONTENDBOOTCAMP-11th/i-land, pull requests merged in 2024-12, with the labels that each got.

#17 📝docs: Pull Request 템플릿 위치 이동(Issue #16 해결)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, P2

#18 ✨feat: Header 컴포넌트 개발 완료(Issue #11 해결)
  jsconfig.json
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icons/cart.svg
  src/assets/icons/heart-fill.svg
  src/assets/icons/heart.svg
  src/assets/icons/logo.svg
  src/assets/icons/no-profile-image.svg
  src/assets/icons/react.svg
  src/assets/icons/search.svg
  src/components/layout/Header.jsx
  src/components/layout/index.jsx
  src/pages/Bookmarks.jsx
  src/pages/Carts.jsx
  src/pages/Search.jsx
  src/pages/index.jsx
  src/pages/user/Login.jsx
  src/routes.jsx
  tailwind.config.js
  vite.config.js
Labels: feature, P1

#25 ✨ feat: 상품 상세 페이지 마크업 작업 완료 (Issue#5 해결)
  src/assets/icons/heart_full_blue.svg
  src/assets/icons/left.svg
  src/assets/icons/minus.svg
  src/assets/icons/plus.svg
  src/assets/icons/right.svg
  src/assets/images/kuromi.png
  src/index.css
  src/pages/detail.html
  tailwind.config.js
Labels: feature, P1

#26 ✨feat: 상품 등록 페이지 마크업 작업 완료 (Issue #9 해결)
  src/components/layout/Header.jsx
  src/index.css
  src/pages/ProductCreate.jsx
  src/routes.jsx
Labels: feature, P1

#24 :sparkles:feat: 메인 페이지 마크업 작업 완료(Issue #3 해결)
  package-lock.json
  package.json
  src/assets/icons/category/comics-anime.svg
  src/assets/icons/category/dolls-figures.svg
  src/assets/icons/category/fashion-clothing.svg
  src/assets/icons/category/idol.svg
  src/assets/icons/category/movie-drama.svg
  src/assets/icons/category/stationaries.svg
  src/assets/icons/chevron-left.svg
  src/assets/icons/chevron-right.svg
  src/assets/icons/heart-fill-s.svg
  src/assets/icons/heart-s.svg
  src/assets/images/favicon-logo.svg
  src/assets/images/image 15.png
  src/assets/images/image 17.png
  src/assets/images/image 18.png
  src/assets/images/image 19.png
  src/assets/images/image 2.png
  src/assets/images/image 20.png
  src/assets/images/image 21.png
  src/assets/images/image 22.png
  src/assets/images/image 23.png
  src/assets/images/image 24.png
  src/assets/images/image 3.png
  src/assets/images/iu.png
  src/assets/images/logo-vertical.svg
  src/assets/images/logo.svg
  src/assets/images/no-profile-image.svg
  src/components/layout/Header.jsx
  src/index.css
  src/pages/main.html
  src/pages/user/login.html
  src/pages/user/signUp.html
  tailwind.config.js
Labels: feature, P1

#27 ✨ feat: 장바구니 페이지 마크업 작업 완료(Issue #6 해결)
  src/assets/icons/x.svg
  src/assets/images/error-char 1.png
  src/pages/cart.html
  src/pages/cartEmpty.html
Labels: feature, P1

#30 :sparkles:feat: 찜한 상품 페이지 마크업 작업 완료(Issue #10 해결)
  src/pages/ProductCreate.jsx
  src/pages/bookmarks.html
  src/pages/bookmarksEmpty.html
  src/pages/detail.html
Labels: feature, P1

#31 ✨feat: 검색 페이지 마크업 작업 완료 (Issue #7 해결)
  package-lock.json
  package.json
  src/assets/icons/close-sm.svg
  src/assets/icons/close.svg
  src/components/SearchNoResult.jsx
  src/index.css
  src/pages/Search.jsx
  src/pages/SearchResults.jsx
  src/pages/main.html
  src/routes.jsx
  tailwind.config.js
Labels: feature, P1

#33 ✨feat: 전체 프로젝트 라우팅 구조 개발 작업 완료 (Issue #32 해결)
  src/pages/Carts.jsx
  src/pages/Create.jsx
  src/pages/Detail.jsx
  src/pages/Main.jsx
  src/pages/Products.jsx
  src/pages/cart.html
  src/pages/user/Signup.jsx
  src/routes.jsx
Labels: feature, P1

#35 ✨ feat: 마크업 파일 JSX 변환 작업 완료(Issue #34 해결)
  src/pages/Bookmarks.jsx
  src/pages/Carts.jsx
  src/pages/Create.jsx
  src/pages/Detail.jsx
  src/pages/Main.jsx
  src/pages/Products.jsx
  src/pages/bookmarks.html
  src/pages/cart.html
  src/pages/detail.html
  src/pages/main.html
  src/pages/user/Login.jsx
  src/pages/user/Signup.jsx
  src/pages/user/login.html
  src/pages/user/signUp.html
Labels: enhancement, P1

#36 ✨feat: 카테고리별 상품 리스트 마크업 개발 작업 완료 (Issue #4 해결)
  src/pages/Products.jsx
Labels: feature, P1
