Repository FRONTENDBOOTCAMP-11th/i-land, pull requests merged in 2025-01, with the labels that each got.

#42 :sparkles:feat: useAxiosInstance 커스텀 훅 추가(Issue #41 해결)
  src/hooks/useAxiosInstance.js
Labels: feature, P2

#43 ✨ feat: 로그인 페이지 기능 구현 완료(Issue #28 해결)
  package-lock.json
  package.json
  src/components/InputError.jsx
  src/components/InputField.jsx
  src/components/PasswordInput.jsx
  src/pages/user/Login.jsx
  src/zustand/userStore.js
Labels: feature, P1

#46 :sparkles:feature: 헤더 컴포넌트 기능 구현(Issue #45 완료)
  src/components/InputField.jsx
  src/components/ProfileDropdown.jsx
  src/components/layout/Header.jsx
  src/pages/user/Login.jsx
  src/zustand/userStore.js
Labels: feature, P1

#47 ✨ feature: 푸터 컴포넌트 구현(issue #12 완료)
  package-lock.json
  package.json
  public/assets/icons/Facebook.svg
  public/assets/icons/Instagram.svg
  public/assets/icons/KakaoTalk.svg
  public/assets/icons/Twitter.svg
  src/components/layout/Footer.jsx
  src/components/layout/index.jsx
Labels: feature, P1

#48 ✨feat: 상품 등록 페이지 1차 기능 구현 완료 (Issue #40 해결)
  package-lock.json
  src/components/InputField.jsx
  src/components/ProductCategory.jsx
  src/components/ProductContent.jsx
  src/components/ProductImageUploader.jsx
  src/pages/Create.jsx
Labels: feature, P1

#52 ✨feat: 공통 컴포넌트 - PrivateRoute 기능 구현 완료 (Issue #51 해결)
  src/components/PrivateRoute.jsx
  src/routes.jsx
Labels: feature, P2

#54 ✨feat: 상품 상세 페이지 기능 구현 완료 (Issue #29 해결)
  package-lock.json
  package.json
  src/components/DetailFooter.jsx
  src/components/DetailHeader.jsx
  src/components/ProductsReview.jsx
  src/pages/Detail.jsx
  src/routes.jsx
Labels: feature, P1

#58 👔enhancement: 컴포 넌트 폴더 구조 개선 구현 완료 (Issue #55 해결)
  src/components/common/InputError.jsx
  src/components/common/InputField.jsx
  src/components/common/PrivateRoute.jsx
  src/components/common/ProfileDropdown.jsx
  src/components/create/ProductCategory.jsx
  src/components/create/ProductContent.jsx
  src/components/create/ProductImageUploader.jsx
  src/components/detail/DetailFooter.jsx
  src/components/detail/DetailHeader.jsx
  src/components/detail/ProductsReview.jsx
  src/components/layout/Header.jsx
  src/components/search/SearchNoResult.jsx
  src/components/user/PasswordInput.jsx
  src/pages/Create.jsx
  src/pages/Detail.jsx
  src/pages/SearchResults.jsx
  src/pages/user/Login.jsx
  src/pages/user/Signup.jsx
  src/routes.jsx
Labels: enhancement, P3

#60 👔enhancement: 상품 등록 시 상품 가격 및 상품 수량 타입 개선 구현 완료 (Issue #59 해결)
  src/pages/Create.jsx
Labels: enhancement, P2

#62 :necktie:enhancement: 푸터 컴포넌트 레이아웃 수정(Issue #61 해결)
  src/components/layout/Footer.jsx
Labels: enhancement, P3

#66 🐞bugfix: 로그인 이후 이전 작업 중인 페이지로 이동 불가 오류 해결(Issue #56 해결)
  src/components/detail/DetailFooter.jsx
  src/hooks/useAxiosInstance.js
  src/pages/Create.jsx
Labels: bugfix, enhancement, P2

#67 :sparkles:feat: 메인 페이지 기능 구현 완료(Issue #50 해결)
  src/components/common/CategoryChip.jsx
  src/components/common/ProductCard.jsx
  src/components/common/ProductLikeBtn.jsx
  src/components/main/MainBanner.jsx
  src/components/main/MainProductList.jsx
  src/components/main/SellerCard.jsx
  src/components/main/TopSellerList.jsx
  src/pages/Main.jsx
  tailwind.config.js
Labels: feature, P1

#69 ✨feat: 장바구니 페이지 기능 구현 완료(Issue #57 해결)
  src/components/carts/CartsBox.jsx
  src/components/carts/CartsDelete.jsx
  src/components/carts/CartsEmpty.jsx
  src/components/carts/CartsPayment.jsx
  src/components/detail/DetailFooter.jsx
  src/components/detail/DetailHeader.jsx
  src/components/detail/ProductsReview.jsx
  src/pages/Carts.jsx
  src/pages/Detail.jsx
  src/pages/cartEmpty.html
Labels: feature, P1

#75 :necktie:enhancement: 메인 페이지 인기 판매자 영역 정렬 기준 수정(Issue #74 해결)
  src/components/main/SellerCard.jsx
  src/components/main/TopSellerList.jsx
  src/pages/Main.jsx
Labels: enhancement, P2

#76 ✨feat: 찜하기 페이지 기능 구현 완료(Issue #68 해결)
  src/components/bookmarks/bookmarksEmpty.jsx
  src/components/carts/CartsBox.jsx
  src/pages/Bookmarks.jsx
  src/pages/bookmarksEmpty.html
Labels: feature, P1

#78 ✨feat: 카테고리별 상품 리스트 페이지 기능 구현 완료 (Issue #53 해결)
  api/bruno-sample/i-land/02.일반 회원/01.상품/01.상품 검색/상품 검색(extra 속성으로 검색, 카테고리가 PC03만 조회).bru
  api/dbinit-sample/i-land/data.js
  api/dbinit-sample/i-land/uploadFiles/category-apparel.png
  api/dbinit-sample/i-land/uploadFiles/category-artist.png
  api/dbinit-sample/i-land/uploadFiles/category-character.png
  api/dbinit-sample/i-land/uploadFiles/category-figurines.png
  api/dbinit-sample/i-land/uploadFiles/category-media.png
  api/dbinit-sample/i-land/uploadFiles/category-stationery.png
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/CategoryCard.jsx
  src/components/common/CategorySection.jsx
  src/components/common/EmptyPage.jsx
  src/pages/Products.jsx
Labels: feature, P1

#81 👔 enhancement: 메인 페이지 상품 카드 컴포넌트 수정(Issue #80 해결)
  src/components/common/ProductCard.jsx
  src/components/main/MainProductList.jsx
  src/pages/Main.jsx
Labels: enhancement, P1

#83 👔enhancement: 공통 컴포넌트 푸터 기능 개선 완료 (Issue #82 해결)
  src/components/layout/index.jsx
  src/index.css
Labels: enhancement, P2

#85 :sparkles:feat: 상품 상세 페이지 찜하기 버튼 기능 구현 완료(Issue #77 해결)
  public/assets/icons/heart_empty.svg
  public/assets/icons/heart_full.svg
  public/assets/icons/heart_full_blue.svg
  src/components/detail/DetailFooter.jsx
  src/components/detail/DetailHeader.jsx
  src/hooks/useAxiosInstance.js
  src/pages/Detail.jsx
Labels: feature, P1

#86 ✨feat: 상품 상세 페이지 상품 후기 수정, 삭제 기능 구현 완료(Issue #79 해결)
  src/components/bookmarks/BookmarksEmpty.jsx
  src/components/detail/AddReview.jsx
  src/components/detail/DetailFooter.jsx
  src/components/detail/ProductsDetailInfomation.jsx
  src/components/detail/ProductsExplanation.jsx
  src/components/detail/ProductsReview.jsx
  src/components/detail/ReviewList.jsx
  src/pages/Bookmarks.jsx
  src/pages/Detail.jsx
  src/pages/Main.jsx
Labels: enhancement, feature, refactor, P1

#89 🐞bugfix: 비회원 상태에서 찜하기 버튼 클릭시 불필요한 메시지 삭제 해결(Issue #88 해결)
  src/components/detail/ProductsDetailInfomation.jsx
Labels: bugfix, P2

#93 :necktie:enhancement: Favicon 수정 및 페이지 Title 수정(Issue #91 해결)
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/pages/Bookmarks.jsx
  src/pages/Carts.jsx
  src/pages/Create.jsx
  src/pages/Detail.jsx
  src/pages/Main.jsx
  src/pages/Products.jsx
  src/pages/Search.jsx
  src/pages/SearchResults.jsx
  src/pages/user/Login.jsx
  src/pages/user/Signup.jsx
Labels: enhancement, P3

#94 ✨feat: 상품 검색 페이지 1차 기능 구현 완료 (Issue #64 해결)
  api/bruno-sample/i-land/02.일반 회원/01.상품/01.상품 검색/상품 검색(기본 검색).bru
  eslint.config.js
  public/assets/icons/KakaoTalk.svg
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/layout/index.jsx
  src/components/search/Search.jsx
  src/components/search/SearchNoResult.jsx
  src/components/search/SearchPopulars.jsx
  src/components/search/SearchRecents.jsx
  src/pages/Search.jsx
  src/pages/SearchResults.jsx
  src/pages/productsList.html
  src/pages/productsList.jsx
  src/routes.jsx
  src/zustand/useSearchStore.js
Labels: feature, P1

#95 👔enhancement: 장바구니 페이지 기능개선 작업(Issue #92 해결)
  src/components/carts/CartsBox.jsx
  src/components/carts/CartsDelete.jsx
  src/components/carts/CartsPayment.jsx
  src/components/detail/ProductsDetailInfomation.jsx
  src/components/detail/ReviewList.jsx
  src/pages/Carts.jsx
  src/pages/Detail.jsx
Labels: bugfix, enhancement, feature, refactor, P1

#98 ✨ feature: 카카오 로그인 기능 구현(Issue #72 해결)
  .gitignore
  index.html
  src/components/common/PrivateRoute.jsx
  src/components/detail/ReviewList.jsx
  src/components/layout/Header.jsx
  src/components/main/SellerCard.jsx
  src/hooks/useAxiosInstance.js
  src/pages/Detail.jsx
  src/pages/users/Login.jsx
  src/pages/users/LoginKakao.jsx
  src/pages/users/Signup.jsx
  src/routes.jsx
Labels: feature, P2

#101 ✨feat: 상품 등록 페이지 카테고리 드롭다운 개선 개발 완료 (Issue #84 해결)
  api/bruno-sample/i-land/06.시스템/03.코드 조회/코드 한건 조회(검색 조건 추가, 부모 카테고리가 PC03인 2단계 카테고리 조회).bru
  package-lock.json
  package.json
  src/components/create/ProductCategory.jsx
  src/pages/Create.jsx
Labels: enhancement, P1

#103 ✨feat: Netlify 404 에러 해결을 위한 파일 설정 완료 (Issue #102 해결)
  netlify.toml
Labels: feature, P1

#105 ✨feat: 페이지 상하단 이동 버튼 구현 완료 (Issue #97 해결)
  package-lock.json
  package.json
  src/components/common/MoveScroll.jsx
  src/components/layout/index.jsx
Labels: feature, P3

#107 🐳chore: @rollup/rollup-darwin-arm64 패키지 설치 완료 (Issue #106 해결)
  package-lock.json
  package.json
Labels: enhancement, P2

#109 ✨feat: 상품 등록 성공 시 상품 등록 성공 페이지 기능 개발 완료 (Issue #104 해결)
  public/assets/images/profile-default.png
  public/assets/images/success.svg
  src/components/create/ProductCreateSuccess.jsx
  src/pages/Create.jsx
  src/pages/Detail.jsx
Labels: enhancement, P2

#112 ✨feat: 메인 페이지 배너 기능 구현 완료 (Issue #111 해결)
  package-lock.json
  package.json
  src/components/main/MainBanner.jsx
  src/index.css
Labels: feature, P3

#114 ✨feat: React Spinner 기능 구현 완료 (Issue #113 해결)
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/Spinner.jsx
  src/hooks/useLoading.js
  src/pages/Bookmarks.jsx
  src/pages/Carts.jsx
  src/pages/Create.jsx
  src/pages/Detail.jsx
  src/pages/Main.jsx
  src/pages/Products.jsx
  src/pages/SearchResults.jsx
  src/zustand/useLoadingStore.js
Labels: feature, P3

#115 :sparkles:feat: 회원정보 조회/수정 페이지 마크업 및 기능 구현 완료(Issue #100 해결)
  public/assets/icons/addimage.svg
  src/components/common/InputField.jsx
  src/components/common/ProfileDropdown.jsx
  src/components/detail/ProductsExplanation.jsx
  src/pages/users/Login.jsx
  src/pages/users/MyInfo.jsx
  src/routes.jsx
Labels: feature, P2

#117 :lipstick:style: Footer 컴포넌트 레이아웃 조정(Issue #116 해결)
  src/components/layout/Footer.jsx
  src/components/main/TopSellerList.jsx
  src/pages/Bookmarks.jsx
  src/pages/users/Login.jsx
  src/pages/users/Signup.jsx
Labels: enhancement, P3

#119 🐳chore: rollup 패키지 optionalDependencies로 이동 완료 (Issue #118 해결)
  package-lock.json
  package.json
Labels: enhancement, P1

#122 🐳chore: compat-data 패키지 버전 올리기 완료 (Issue #121 해결)
  package-lock.json
Labels: enhancement, P1

#123 [deploy] I-Land 프로젝트 3차 배포
  .gitignore
  api/bruno-sample/i-land/02.일반 회원/01.상품/01.상품 검색/상품 검색(기본 검색).bru
  api/bruno-sample/i-land/06.시스템/03.코드 조회/코드 한건 조회(검색 조건 추가, 부모 카테고리가 PC03인 2단계 카테고리 조회).bru
  eslint.config.js
  index.html
  netlify.toml
  package-lock.json
  package.json
  public/assets/icons/KakaoTalk.svg
  public/assets/icons/addimage.svg
  public/assets/images/profile-default.png
  public/assets/images/success.svg
  src/App.jsx
  src/components/carts/CartsBox.jsx
  src/components/carts/CartsDelete.jsx
  src/components/carts/CartsPayment.jsx
  src/components/common/InputField.jsx
  src/components/common/MoveScroll.jsx
  src/components/common/PrivateRoute.jsx
  src/components/common/ProfileDropdown.jsx
  src/components/common/Spinner.jsx
  src/components/create/ProductCategory.jsx
  src/components/create/ProductCreateSuccess.jsx
  src/components/detail/ProductsDetailInfomation.jsx
  src/components/detail/ProductsExplanation.jsx
  src/components/detail/ReviewList.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/layout/index.jsx
  src/components/main/MainBanner.jsx
  src/components/main/SellerCard.jsx
  src/components/main/TopSellerList.jsx
  src/components/search/Search.jsx
  src/components/search/SearchNoResult.jsx
  src/components/search/SearchPopulars.jsx
  src/components/search/SearchRecents.jsx
  src/hooks/useAxiosInstance.js
  src/hooks/useLoading.js
  src/index.css
  src/pages/Bookmarks.jsx
  src/pages/Carts.jsx
  src/pages/Create.jsx
  src/pages/Detail.jsx
  src/pages/Main.jsx
  src/pages/Products.jsx
  src/pages/Search.jsx
  src/pages/SearchResults.jsx
  src/pages/productsList.html
  src/pages/productsList.jsx
  src/pages/user/Login.jsx
  src/pages/user/Signup.jsx
  src/pages/users/Login.jsx
  src/pages/users/LoginKakao.jsx
  src/pages/users/MyInfo.jsx
  src/pages/users/Signup.jsx
  src/routes.jsx
  src/zustand/useLoadingStore.js
  src/zustand/useSearchStore.js
Labels: feature, P1

#125 🐞bugfix: netlify.toml 파일 내 오타 수정 완료 (Issue #124 해결)
  netlify.toml
Labels: bugfix, P1

#126 [deploy] I-Land 프로젝트 3.0.1 배포
  netlify.toml
Labels: bugfix, P1

#110 ✨feat: 장바구니, 상품 상세 페이지 구매 기능 구현 완료 (Issue #108 해결)
  eslint.config.js
  package-lock.json
  src/components/carts/CartsBox.jsx
  src/components/carts/CartsDelete.jsx
  src/components/carts/CartsPayment.jsx
  src/components/common/MoveScroll.jsx
  src/components/detail/ProductsDetailInfomation.jsx
  src/components/detail/ReviewList.jsx
  src/pages/Bookmarks.jsx
  src/pages/Carts.jsx
  src/pages/Detail.jsx
  src/pages/Payment.jsx
  src/routes.jsx
Labels: feature, P1

#130 👔enhancement: 필요 없는 파일 삭제 완료 (Issue #129 해결)
  src/pages/productsList.html
  src/pages/productsList.jsx
  src/utils/categories.js
Labels: enhancement, P3

#132 :sparkles:feat: 상품 정렬 기능 구현(Issue #128 해결)
  src/components/search/Search.jsx
  src/pages/Detail.jsx
  src/pages/Products.jsx
  src/pages/SearchResults.jsx
Labels: feature, P2

#135 📝docs: README.md 파일 작성 완료 (Issue #134 해결)
  README.md
Labels: documentation

#137 ✨feat: 상품 등록 페이지에서 상품 이미지 등록 시 이미지 미리보기 기능 구현 완료 (Issue #131 해결)
  src/components/create/ProductImageUploader.jsx
  src/pages/Create.jsx
Labels: feature, P2

#138 👔 enhancement: 상품 이미지 없는 경우 및 상품 이미지 정방형이 아닌 경우 대응(Issue #136 해결)
  src/components/common/ProductCard.jsx
  src/components/detail/ProductsDetailInfomation.jsx
Labels: enhancement, P3

#140 :necktie:enhancement: 상품 카드 이미지 마우스 호버 시 이미지 확대/축소 완료(Issue #139 해결)
  src/components/common/CategoryCard.jsx
  src/components/common/ProductCard.jsx
Labels: enhancement, P3

#142 👔enhancement: 결과 없음 페이지 공통 컴포넌트화 작업 완료 (Issue #141 해결)
  src/components/bookmarks/BookmarksEmpty.jsx
  src/components/carts/CartsEmpty.jsx
  src/components/common/EmptyPage.jsx
  src/components/common/EmptyState.jsx
  src/components/search/SearchNoResult.jsx
  src/pages/Bookmarks.jsx
  src/pages/Carts.jsx
  src/pages/Products.jsx
  src/pages/SearchResults.jsx
Labels: enhancement, P3

#146 🐞bugfix: 불필요한 코드 삭제 및 빈 페이지 간격 수정 완료 (Issue #143 해결)
  src/components/carts/CartsDelete.jsx
  src/pages/Bookmarks.jsx
  src/pages/Carts.jsx
Labels: bugfix, refactor, P2

#148 ✨ feat: 상품 미구매시 후기등록함수 차단 기능 구현 완료 (Issue #147 해결)
  src/pages/Detail.jsx
Labels: feature, P2

#149 :sparkles:feat: 상품 구매 내역 페이지 마크업 및 기능 구현 완료(Issue #145 해결)
  src/components/common/ProfileDropdown.jsx
  src/components/myPurchase/MyPurchaseCard.jsx
  src/components/myPurchase/PurchaseContent.jsx
  src/pages/MyPurchase.jsx
  src/routes.jsx
Labels: feature, P2

#151 🐞bugfix: 비회원 상태에서 상품상세페이지 이동불가 현상 수정 (Issue #150 해결)
  src/pages/Detail.jsx
Labels: bugfix, refactor, P1

#154 🐞bugfix: MyPurchase.jsx import 수정(Issue #153 해결)
  src/pages/MyPurchase.jsx
Labels: bugfix, P1

#152 [deploy] I-Land 프로젝트 4차 배포
  README.md
  eslint.config.js
  package-lock.json
  src/components/bookmarks/BookmarksEmpty.jsx
  src/components/carts/CartsBox.jsx
  src/components/carts/CartsDelete.jsx
  src/components/carts/CartsEmpty.jsx
  src/components/carts/CartsPayment.jsx
  src/components/common/CategoryCard.jsx
  src/components/common/EmptyPage.jsx
  src/components/common/EmptyState.jsx
  src/components/common/MoveScroll.jsx
  src/components/common/ProductCard.jsx
  src/components/common/ProfileDropdown.jsx
  src/components/create/ProductImageUploader.jsx
  src/components/detail/ProductsDetailInfomation.jsx
  src/components/detail/ReviewList.jsx
  src/components/myPurchase/MyPurchaseCard.jsx
  src/components/myPurchase/PurchaseContent.jsx
  src/components/search/Search.jsx
  src/components/search/SearchNoResult.jsx
  src/pages/Bookmarks.jsx
  src/pages/Carts.jsx
  src/pages/Create.jsx
  src/pages/Detail.jsx
  src/pages/MyPurchase.jsx
  src/pages/Payment.jsx
  src/pages/Products.jsx
  src/pages/SearchResults.jsx
  src/pages/productsList.html
  src/pages/productsList.jsx
  src/routes.jsx
  src/utils/categories.js
Labels: feature, P1

#155 Update README.md
  README.md
Labels: documentation, P3
